config/routes.rb
Rails.application.routes.draw do
  resources :organizations, only: [:index, :create, :update, :edit] do
    resources :groups, only: [:index, :create, :update, :edit] do
      post   'add_member'
      delete 'delete_member'
    end
    resources :schedules do
      get 'pager', on: :collection
    end

    member do
      get 'members'
      get 'add_member'
      delete 'delete_member'
    end
  end

  root to: 'top#index'

  # For OmniAuth
  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout
end

app/models/group.rb
class Group < ActiveRecord::Base
  ## アソシエーション
  belongs_to :user
  belongs_to :organization
  has_many   :member, class_name: 'Member::GroupMember'
  has_many   :participations
  has_many   :schedules, through: :participations

  ## バリデーション
  validates :name, presence: true

  ## スコープ
  scope :belong, -> (user, organization) { where(groups: { id: Member::GroupMember.where(organization_id: organization.id, user_id: user.id).pluck(:group_id) }) }

  ## コールバック
  after_create { |group| Member::GroupMember.create(organization_id: group.organization_id, group_id: group.id, user_id: group.user_id) }

  # メンバー追加済みか
  def added?(org_member)
    Member::GroupMember.where(organization_id: org_member.organization_id, group_id: self.id, user_id: org_member.user_id).exists?
  end

  # オーナーか(オーナー==作成者)
  def owner?(user)
    self.user_id == user.id
  end
end

app/controllers/concerns/groups_controller.rb
class GroupsController < ApplicationController
  permits :name

  # 一覧
  def index(organization_id)
    @organization = Organization.find_by(id: organization_id)
    @groups       = Group.where(organization_id: organization_id).order(created_at: :asc)
    @group        = Group.new
  end

  # 作成
  def create(organization_id, group)
    @group = Group.new(group)
    @group.user_id         = current_user.id
    @group.organization_id = organization_id
    @group.save!

    redirect_to organization_groups_path(organization_id) and return
  end

  # 編集
  def edit(organization_id, id)
    @group        = Group.find_by(id: id)
    @organization = Organization.find_by(id: organization_id)
    @group_members        = Member::GroupMember.where(organization_id: organization_id, group_id: id).order(created_at: :asc)
    @organization_members = Member::OrganizationMember.where(organization_id: organization_id).where.not(user_id: @group_members.pluck(:user_id)).order(created_at: :asc)
  end

  # 更新
  def update(organization_id, id, group)
    @group = Group.find_by(id: id)
    @group.update!(group.permit!)

    redirect_to organization_groups_path(@group.organization_id) and return
  end

  # メンバー追加
  def add_member(organization_id, group_id, user_id)
    Member::GroupMember.where(organization_id: organization_id, group_id: group_id, user_id: user_id).first_or_create!

    redirect_to edit_organization_group_path(organization_id, group_id) and return
  end

  # メンバー削除
  def delete_member(organization_id, group_id, user_id)
    member = Member::GroupMember.find_by(organization_id: organization_id, group_id: group_id, user_id: user_id)
    member.destroy!

    redirect_to edit_organization_group_path(organization_id, group_id) and return
  end
end

app/views/groups/edit.html.haml
- if @group.owner?(current_user)
  %h2 Edit Group

  = form_for @group, url: organization_group_path(@group.organization_id, @group) do |f|
    %fieldset
      .form-group
        %label.col-lg-2.control-label{:for => "inputEmail"} Name
        .col-lg-10
          = f.text_field :name, class: 'form-control'

%br
%h2 Group Members

%table.table.table-striped.table-hover
  %tbody
    %tr
      %th No.
      %th メンバー名
      %th
    - @group_members.each.with_index(1) do |group_member, index|
      %tr
        %td= index
        %td= group_member.user.try(:name)
        %td
          - if @group.user_id != group_member.user_id and @group.owner?(current_user)
            = link_to 'グループから除外', organization_group_delete_member_path(@organization, @group, user_id: group_member.user_id), method: :delete, data: { confirm: "「#{group_member.user.try(:name)}」をメンバーから除外します。よろしいですか？" }

%br
%h2 Organization Members(Not group member)

%table.table.table-striped.table-hover
  %tbody
    %tr
      %th No.
      %th メンバー名
      %th
    - @organization_members.each.with_index(1) do |organization_member, index|
      %tr
        %td= index
        %td= organization_member.user.try(:name)
        %td
          - if @group.user_id != organization_member.user_id and @group.owner?(current_user)
            = link_to 'グループへ追加', organization_group_add_member_path(@organization, @group, user_id: organization_member.user_id), method: :post, data: { confirm: "「#{organization_member.user.try(:name)}」をメンバーに追加します。よろしいですか？" }

app/views/groups/index.html.haml
%h2 Groups

= form_for @group, url: organization_groups_path(@organization) do |f|
  %fieldset
    .form-group
      %label.col-lg-2.control-label{:for => "inputEmail"} Name
      .col-lg-10
        = f.text_field :name, class: 'form-control'
%br

%table.table.table-striped.table-hover
  %tbody
    %tr
      %th No.
      %th グループ名
    - @groups.each.with_index(1) do |group, index|
      %tr
        %td= index
        %td= link_to group.name, edit_organization_group_path(group.organization_id, group)