config/routes.rb
Rails.application.routes.draw do
  resources :organizations, only: [:index, :create, :update, :edit] do
    resources :groups, only: [:index, :create, :update, :edit] do
      post   'add_member'
      delete 'delete_member'
    end
    resources :schedules do
      get 'pager', on: :collection
    end

    member do
      get 'members'
      get 'add_member'
      delete 'delete_member'
    end
  end

  root to: 'top#index'

  # For OmniAuth
  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  ## アソシエーション
  belongs_to :user
  belongs_to :organization
  # belongs_to :group
  belongs_to :repeat_setting
  has_many   :participations, dependent: :destroy
  has_many   :groups, through: :participations

  ## バリデーション
  validates :title, presence: true

  ## スコープ
  scope :mine, ->(user) { where( schedules: { user_id: user.id } ) }

  ## クラスメソッド
  # スケジュールハッシュ生成
  def self.generate_schedule_hash(current_date, user, organization_id)
    schedule_hash = Hash.new{ |hash, key| hash[key] = Array.new }
    # schedules = Schedule.where(organization_id: organization_id).where(start_at: (current_date.beginning_of_month.beginning_of_day..current_date.end_of_month.end_of_day)).order("schedules.start_at ASC")
    schedules = Schedule.where(organization_id: organization_id, user_id: user.id).where(start_at: (current_date.beginning_of_month.beginning_of_day..current_date.end_of_month.end_of_day)).order("schedules.start_at ASC")
    schedules.each do |schedule|
      schedule_hash[schedule.start_at.strftime("%Y_%m_%d")].push(schedule)
    end

    return schedule_hash
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  permits :repeat_setting, :title, :note, :start_at, :end_at

  before_action :set_organization
  before_action :check_member

  # スケジュール一覧(カレンダー)
  def index(current_date: nil, organization_id: nil)
    # @schedules = Schedule.where(organization_id: @organization.id)

    @current_date = current_date.present? ? Date.parse(current_date) : Date.today

    # スケジュールハッシュ生成
    @schedule_hash = Schedule.generate_schedule_hash(@current_date, current_user, organization_id)
  end

  # GET /schedules/1
  def show(id)
    @schedule = Schedule.find_by(id: id, user_id: current_user.id)
  end

  # GET /schedules/new
  def new(organization_id, day)
    @schedule = Schedule.new
    @day      = Date.parse(day)
  end

  # GET /schedules/1/edit
  def edit(id, day)
    @schedule = Schedule.find_by(id: id, user_id: current_user.id)
    @day      = Date.parse(day)
  end

  # POST /schedules
  def create(organization_id, schedule, group_ids: nil)
    @schedule = Schedule.new(schedule)
    @schedule.user_id         = current_user.id
    @schedule.organization_id = organization_id

    if @schedule.save
      # グループ紐付け
      if group_ids.present?
        group_ids.each do |group_id|
          Participation.create(schedule_id: @schedule.id, group_id: group_id, organization_id: organization_id)
        end
      end

      redirect_to organization_schedules_path(@schedule.organization_id, current_date: @schedule.start_at.to_date)
    else
      render :new
    end
  end

  # PUT /schedules/1
  def update(id, schedule, group_ids: nil)
    @schedule = Schedule.find_by(id: id, user_id: current_user.id)

    if @schedule.update(schedule)
      # グループ紐付け
      if group_ids.present?
        delete_group_ids = @schedule.group_ids - group_ids.map{|x| x.to_i }

        group_ids.each do |group_id|
          Participation.where(schedule_id: @schedule.id, group_id: group_id, organization_id: @schedule.organization_id).first_or_create
        end
      end

      Participation.where(schedule_id: @schedule.id, group_id: delete_group_ids, organization_id: @schedule.organization_id).delete_all

      redirect_to organization_schedules_path(@schedule.organization_id, current_date: @schedule.start_at.to_date)
    else
      render :edit
    end
  end

  # DELETE /schedules/1
  def destroy(organization_id, id)
    @schedule = Schedule.find_by(organization_id: organization_id, id: id, user_id: current_user.id)
    @schedule.destroy

    redirect_to organization_schedules_path(@schedule.organization_id, current_date: @schedule.start_at.to_date), notice: "「#{@schedule.title}」を削除しました。" and return
  end

  # オートページャー
  def pager(target_month: nil, page: 1, organization_id: nil)
    current_date = target_month.present? ? Date.parse("#{target_month}-01") : Date.today
    current_date = Date.parse(current_date.since(page.to_i.month).strftime("%Y-%m-01"))

    # スケジュールハッシュ生成
    schedule_hash = Schedule.generate_schedule_hash(current_date, current_user, organization_id)

    render partial: '/schedules/calendar', locals: { organization: Organization.find(organization_id), current_date: current_date, schedule_hash: schedule_hash, current_page: (page.to_i + 1) }
  end

  private

  # 組織情報取得
  def set_organization
    @organization = Organization.find_by(id: params[:organization_id])

    redirect_to root_path, alert: '組織情報がありません。' and return if @organization.blank?
  end

  # 組織情報取得
  def check_member
    unless Member::OrganizationMember.where(organization_id: params[:organization_id], user_id: current_user.id).exists?
      redirect_to root_path, alert: 'メンバーとして登録されていません。' and return
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_calendar.html.haml
%div{ id: "page_#{current_page}" }
  %ul.pagination
    %li= link_to "今月", organization_schedules_path(organization, current_date: Time.now.strftime("%Y-%m-01"))
  %br
  %ul.pagination
    %li= link_to "前月", organization_schedules_path(organization, current_date: current_date.ago(1.month).strftime("%Y-%m-01"))
    %li= link_to "次月", organization_schedules_path(organization, current_date: current_date.since(1.month).strftime("%Y-%m-01"))

  %h4= current_date.strftime("%Y年%m月")
  .calendar_area
    %table.calendar
      %tr
        %th.sunday 日
        %th 月
        %th 火
        %th 水
        %th 木
        %th 金
        %th.saturday 土
      %tr
        - current_date.beginning_of_month.wday.times do
          %td
            %br
        - (current_date.beginning_of_month..current_date.end_of_month).each do |day|
          - if day.wday == 0
            %tr
          %td{ class: "#{day_class(day)} #{today_class(day)}" }
            - # 日付表示
            -# = link_to day.day, '#', rel: 'tooltip', data: { toggle: 'modal', title: HolidayJapan.name(day), target: "#new_modal_#{day.strftime("%Y_%m_%d")}" }
            = link_to day.day, new_organization_schedule_path(organization, day: day), rel: 'tooltip', data: { title: HolidayJapan.name(day), target: "#new_modal_#{day.strftime("%Y_%m_%d")}" }

            -# - # スケジュール新規作成モーダル
            -# = render partial: '/schedules/new_schedule_modal', locals: { organization: organization, schedule: Schedule.new, day: day }

            %br
            - schedules = schedule_hash[day.strftime("%Y_%m_%d")]
            - if schedules.present?
              - schedules.each do |schedule|
                - # スケジュール表示
                %span{ style: 'color: #000;' }
                  - # スケジュールタイトル
                  -# = link_to s.title, '#', rel: 'popover', data: { toggle: 'modal', title: schedule_popover_title(s), content: markdown(s.note), target: "#edit_modal_#{s.id}" }
                  = link_to schedule.title, edit_organization_schedule_path(organization, schedule, day: day), rel: 'popover', data: { title: schedule_popover_title(schedule), content: markdown(schedule.note) }

                  -# - # スケジュール編集モーダル
                  -# = render partial: '/schedules/edit_schedule_modal', locals: { organization: organization, schedule: s, day: day }
                %br
        - (6 - current_date.end_of_month.wday).times do
          %td
            %br
  %br

app/views/schedules/_form.html.haml
.form-group
  = f.label :title, class: 'col-lg-2 control-label'
  .col-lg-10
    = f.text_field :title, class: 'form-control'
.form-group
  = f.label :note, class: 'col-lg-2 control-label'
  .col-lg-10
    = f.text_area :note, rows: 10, class: 'form-control'
.form-group
  = f.label :start_at, class: 'col-lg-2 control-label'
  .col-lg-10
    = f.datetime_select :start_at, { class: 'form-control', minute_step: 5, use_month_numbers: true, date_separator: ' ', datetime_separator: '　', time_separator: ' : ', default: day }
.form-group
  = f.label :end_at, class: 'col-lg-2 control-label'
  .col-lg-10
    = f.datetime_select :end_at, { class: 'form-control', minute_step: 5, use_month_numbers: true, date_separator: ' ', datetime_separator: '　', time_separator: ' : ', default: day }

参加グループ：
- organization.groups.belong(current_user, organization).order(name: :asc).each do |group|
  %li
    = check_box_tag 'group_ids[]', group.id, f.object.group_ids.index(group.id), id: "#{day.strftime("%Y_%m%d")}_#{f.object.id.to_i}_group_#{group.id}"
    = label_tag("#{day.strftime("%Y_%m%d")}_#{f.object.id.to_i}_group_#{group.id}", group.name)

app/views/schedules/edit.html.haml
= form_for @schedule, url: organization_schedule_path(@schedule.organization, @schedule), method: :put, html: { class: 'form-horizontal', role: 'form' } do |f|
  .modal-header
    %h4.modal-title Edit Schedule
  .modal-body
    = render partial: '/schedules/form', locals: { f: f, day: @day, organization: @schedule.organization }
  .modal-footer
    = link_to 'Delete', organization_schedule_path(@schedule.organization, @schedule), method: :delete, data: { confirm: "「#{@schedule.title}」を削除します。よろしいですか？" }, class: 'btn btn-default'
    = f.submit 'Save', data: { disable_with: 'Save' }, class: 'btn btn-primary'

app/views/schedules/index.html.haml
%h2 Schedules

%h3= link_to(@current_date.strftime("%Y年"), organization_schedules_path(@organization, current_date: Time.now.strftime("%Y-%m-01")))

%ul.pagination
  - 1.upto(12) do |month|
    %li{ class: (@current_date.month == month ? 'active' : '') }
      = link_to "#{month}月", organization_schedules_path(@organization, current_date: "#{@current_date.year}-#{month}-01")
%br
%br

- # カレンダー表示
= render partial: '/schedules/calendar', locals: { organization: @organization, current_date: @current_date, schedule_hash: @schedule_hash, current_page: 1 }

- # オートページャー用パラメータ
= hidden_field_tag :autopager_on, true
= hidden_field_tag :target_month, @current_date.strftime("%Y-%m")
= hidden_field_tag :current_page, 1
= hidden_field_tag :pager_schedules_path, pager_organization_schedules_path(@organization)

app/views/schedules/new.html.haml
= form_for @schedule, url: organization_schedules_path(@organization), html: { class: 'form-horizontal', role: 'form' } do |f|
  .modal-header
    %h4.modal-title New Schedule
  .modal-body
    = render partial: '/schedules/form', locals: { f: f, day: @day, organization: @organization }
  .modal-footer
    = f.submit 'Save', data: { disable_with: 'Save' }, class: 'btn btn-primary'



-# .modal.fade{ id: "new_modal_#{day.strftime("%Y_%m_%d")}" }
-#   .modal-dialog
-#     .modal-content
-#       = form_for schedule, url: organization_schedules_path(organization), html: { class: 'form-horizontal', role: 'form' } do |f|
-#         .modal-header
-#           %h4.modal-title New Schedule
-#         .modal-body
-#           = render partial: '/schedules/form_modal', locals: { f: f, day: day, organization: organization }
-#         .modal-footer
-#           %button.btn.btn-default{ data: { dismiss: 'modal' }, type: 'button' } Close
-#           = f.submit 'Save', data: { disable_with: 'Save' }, class: 'btn btn-primary'