config/routes.rb
Rails.application.routes.draw do
  resources :organizations, only: [:index, :create, :update, :edit] do
    resources :groups, only: [:index, :create, :update, :edit] do
      post   'add_member'
      delete 'delete_member'
    end
    resources :schedules do
      get 'pager', on: :collection
    end

    member do
      get 'members'
      get 'add_member'
      delete 'delete_member'
    end
  end

  root to: 'top#index'

  # For OmniAuth
  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  ## アソシエーション
  belongs_to :user
  has_many   :groups
  has_many   :member, class_name: 'Member::OrganizationMember'

  ## バリデーション
  validates :name, presence: true

  ## スコープ
  scope :belong, -> (user) { where(organizations: { id: user.members.pluck(:organization_id) }) }

  ## コールバック
  after_create { |organization| Member::OrganizationMember.create(organization_id: organization.id, user_id: organization.user_id) }

  def owner?(user)
    self.user_id == user.try(:id)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  permits :name

  before_action :set_organization, except: [:index, :create]

  # 一覧
  def index
    @organizations = Organization.order(created_at: :asc).all
    @organization  = Organization.new
  end

  # 作成
  def create(organization)
    @organization = Organization.new(organization)
    @organization.user_id = current_user.id
    @organization.save!

    redirect_to organizations_path and return
  end

  # 編集
  def edit(id)
    @organization = Organization.find_by(id: id)
  end

  # 更新
  def update(id, organization)
    @organization = Organization.find_by(id: id)
    @organization.update!(organization.permit!)

    redirect_to organizations_path and return
  end

  # メンバー一覧
  def members(id)
    @members = Member::OrganizationMember.where(organization_id: id)

    if @organization.invite_token.blank?
      @organization.update!(invite_token: SecureRandom.hex(16))
    end
  end

  # メンバー追加
  def add_member(id, invite_token)
    organization = Organization.find_by(id: id, invite_token: invite_token)

    redirect_to root_path, alert: '組織情報がありません。' and return if organization.blank?

    Member::OrganizationMember.where(organization_id: organization.id, user_id: current_user.id).first_or_create!

    redirect_to organization_schedules_path(organization) and return
  end

  # メンバー削除
  def delete_member(id, member_id)
    member = Member::OrganizationMember.find_by(id: member_id, organization_id: id)
    member.destroy!

    redirect_to members_organization_path(@organization) and return
  end

  private

  # 組織情報取得
  def set_organization
    @organization = Organization.find_by(id: params[:id])

    redirect_to root_path, alert: '組織情報がありません。' and return if @organization.blank?
  end
end

app/views/organizations/edit.html.haml
%h2 Edit Organization

= form_for @organization, url: organization_path(@organization) do |f|
  %fieldset
    .form-group
      %label.col-lg-2.control-label{:for => "inputEmail"} Name
      .col-lg-10
        = f.text_field :name, class: 'form-control'

app/views/organizations/index.html.haml
%h2 Organizations

= form_for @organization do |f|
  %fieldset
    .form-group
      %label.col-lg-2.control-label{:for => "inputEmail"} Name
      .col-lg-10
        = f.text_field :name, class: 'form-control'
%br

%table.table.table-striped.table-hover
  %tbody
    %tr
      %th 作成者
      %th 組織名
    - @organizations.each do |organization|
      %tr
        %td= organization.user.try(:name)
        %td= link_to organization.name, edit_organization_path(organization)

app/views/organizations/members.html.haml
%h2 Organization Members

- if @organization.owner?(current_user)
  %p
    招待リンク:
    %br
    = link_to add_member_organization_url(@organization, invite_token: @organization.invite_token), add_member_organization_url(@organization, invite_token: @organization.invite_token)

%table.table.table-striped.table-hover
  %tbody
    %tr
      %th No.
      %th メンバー名
      %th
    - @members.each.with_index(1) do |member, index|
      %tr
        %td= index
        %td= member.user.try(:name)
        %td
          - if current_user.id != member.user_id and @organization.user_id != member.user_id
            = link_to 'メンバー解除', delete_member_organization_path(@organization, member_id: member.id), method: :delete, data: { confirm: "「#{member.user.try(:name)}」をメンバーから除外します。よろしいですか？" }