config/routes.rb
Rails.application.routes.draw do
  resources :organizations, only: [:index, :create, :update, :edit] do
    resources :groups, only: [:index, :create, :update, :edit] do
      post   'add_member'
      delete 'delete_member'
    end
    resources :schedules do
      get 'pager', on: :collection
    end

    member do
      get 'members'
      get 'add_member'
      delete 'delete_member'
    end
  end

  root to: 'top#index'

  # For OmniAuth
  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout
end

app/views/layouts/_user_icon.html.haml
- if user.present?
  = link_to_unless(user.name.blank?, image_tag(user.image, size: size, class: klass), "#{Settings[user.last_login_provider + '_page']}#{user.name}", target: "_blank", title: user.name, rel: "tooltip", "data-original-title" => user.name)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= Settings.app_name
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  %body{ 'data-no-turbolink' => true }
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          - # ロゴリンク
          - if @organization.try(:id).present?
            = link_to @organization.name, organization_schedules_path(@organization), class: 'navbar-brand'
          - else
            = link_to Settings.app_name, root_path, class: 'navbar-brand'
          %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbar-main.navbar-collapse.collapse
          %ul.nav.navbar-nav
            - if current_user.present?
              - # 組織メニュー
              %li.dropdown
                = link_to '#', id: 'organizations_menu', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
                  Organizations
                  %span.caret
                %ul.dropdown-menu{ "aria-labelledby" => "organizations_menu" }
                  %li= link_to 'New Organizations', organizations_path
                  - # Organization一覧
                  - Organization.belong(current_user).each do |organization|
                    %li= link_to organization.name, organization_schedules_path(organization)
              - if @organization.try(:id).present?
                - # グループ一覧
                %li= link_to 'Groups', organization_groups_path(@organization)

                - # 組織メンバー
                %li= link_to 'Members', members_organization_path(@organization)

                - # スケジュール
                %li= link_to 'Schedules', organization_schedules_path(@organization)

              -# %li= link_to 'Groups', organization_groups_path
              -# %li= link_to 'Schedules', schedules_path

            -# %li.dropdown
            -#   %a#themes.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            -#     Themes
            -#     %span.caret
            -#   %ul.dropdown-menu{"aria-labelledby" => "themes"}
            -#     %li
            -#       %a{:href => "../default/"} Default
            -#     %li.divider
            -#     %li
            -#       %a{:href => "../cerulean/"} Cerulean
            -#     %li
            -#       %a{:href => "../cosmo/"} Cosmo
            -#     %li
            -#       %a{:href => "../cyborg/"} Cyborg
            -# %li
            -#   %a{:href => "../help/"} Help
            -# %li
            -#   %a{:href => "http://news.bootswatch.com"} Blog
            -# %li.dropdown
            -#   %a#download.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            -#     Download
            -#     %span.caret
            -#   %ul.dropdown-menu{"aria-labelledby" => "download"}
            -#     %li
            -#       %a{:href => "./bootstrap.min.css"} bootstrap.min.css
            -#     %li
            -#       %a{:href => "./bootstrap.css"} bootstrap.css
            -#     %li.divider
            -#     %li
            -#       %a{:href => "./variables.less"} variables.less
            -#     %li
            -#       %a{:href => "./bootswatch.less"} bootswatch.less
          %ul.nav.navbar-nav.navbar-right
            -# %li
            -#   %a{:href => "http://builtwithbootstrap.com/", :target => "_blank"} Built With Bootstrap
            -# %li
            -#   %a{:href => "https://wrapbootstrap.com/?ref=bsw", :target => "_blank"} WrapBootstrap
            - unless signed_in?
              %li= link_to 'Login', '/auth/facebook'
            - else
              %li= link_to "Logout", logout_path
    .container{ style: 'margin-top: 50px;' }
      %p
        = simple_format(flash[:notice], style: "color: green;") if flash[:notice].present?
        = simple_format(flash[:alert], style: "color: red;")    if flash[:alert].present?

      = yield

    %br/
    %br/

    -# %center
    -#   Developed by
    -#   = succeed "," do
    -#     %a{ href: "https://twitter.com/#{Settings.programmer_twitter_id}/", target: '_blank' }
    -#       = "@#{Settings.programmer_twitter_id}"
    -#   Designed by
    -#   = succeed "," do
    -#     %a{ href: "https://twitter.com/#{Settings.designer_twitter_id}/", target: '_blank' }
    -#       = "@#{Settings.designer_twitter_id}"
    -#   Licence by
    -#   %a{ href: 'https://creativecommons.org/licenses/by-nc-sa/2.1/jp/', target: '_blank' }
    -#     CC BY-NC-SA 2.1